# Generated by Django 3.0 on 2021-08-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201021_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
