# Generated by Django 4.0.dev20210701104232 on 2021-07-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diligencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diligencia',
            options={'verbose_name': 'Diligência', 'verbose_name_plural': 'Diligências'},
        ),
    ]
