# Generated by Django 3.0 on 2021-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressline1', models.CharField(db_column='AddressLine1', max_length=60)),
                ('addressline2', models.CharField(blank=True, db_column='AddressLine2', max_length=60, null=True)),
                ('city', models.CharField(db_column='City', max_length=30)),
                ('stateprovince', models.CharField(db_column='StateProvince', max_length=50)),
                ('countryregion', models.CharField(db_column='CountryRegion', max_length=50)),
                ('postalcode', models.CharField(db_column='PostalCode', max_length=15)),
                ('rowguid', models.UUIDField(db_column='rowguid', editable=False, primary_key=True, serialize=False)),
                ('modifieddate', models.DateTimeField(auto_now_add=True, db_column=' ModifiedDate')),
            ],
            options={
                'db_table': 'Endereços',
                'managed': False,
            },
        ),
    ]
