# Generated by Django 3.0 on 2021-07-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='SalesLT"."Address',
        ),
    ]
