# Generated by Django 3.0 on 2021-07-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210723_0943'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='[SalesLT].[Address]',
        ),
    ]
