# Generated by Django 3.0 on 2021-07-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210723_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'managed': False, 'ordering': ['id_curso'], 'verbose_name_plural': 'Cursos'},
        ),
    ]
