# Generated by Django 3.0 on 2021-08-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210726_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(db_column='Produto', max_length=100)),
                ('loja_digital', models.CharField(db_column='Loja Digital', max_length=100)),
                ('info_adicional', models.CharField(db_column='Info Adicional', max_length=100)),
                ('tipo_operacao', models.CharField(db_column='Tipo Operacao', max_length=100)),
                ('valor_orig', models.CharField(db_column='Valor Orig', max_length=100)),
                ('valor_selo', models.CharField(db_column='Valor Selo', max_length=100)),
                ('isrc', models.CharField(db_column='ISRC', max_length=100)),
                ('nome_faixa', models.CharField(db_column='Nome Faixa', max_length=100)),
                ('quant', models.CharField(db_column='Quant', max_length=100)),
                ('data_fato', models.CharField(db_column='Data Fato', max_length=100)),
                ('artista', models.CharField(db_column='Artista', max_length=100)),
                ('titulo', models.CharField(db_column='Titulo', max_length=100)),
                ('territorio', models.CharField(db_column='Territorio', max_length=100)),
                ('data_relat', models.CharField(db_column='Data Relat', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Finaceiro',
                'db_table': 'Financeiro',
                'managed': False,
            },
        ),
    ]
