# Generated by Django 3.0 on 2021-08-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_financeiro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
