# Generated by Django 3.2 on 2021-08-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrinho',
            new_name='Carro',
        ),
        migrations.RenameModel(
            old_name='CarrinhoProduto',
            new_name='CarroProduto',
        ),
    ]
