# Generated by Django 3.0 on 2021-08-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_aluno', models.IntegerField(db_column='id_aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=200)),
                ('data_nascimento', models.DateField(db_column='data_nascimento')),
                ('sexo', models.CharField(db_column='sexo', max_length=1)),
                ('data_cadastro', models.DateTimeField(db_column='data_cadastro')),
                ('login_cadastro', models.CharField(db_column='login_cadastro', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'db_table': 'ALUNOS',
                'ordering': ['id_aluno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alunosxturmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(db_column='valor', decimal_places=2, max_digits=13)),
                ('valor_desconto', models.DecimalField(blank=True, db_column='valor_desconto', decimal_places=2, max_digits=3, null=True)),
                ('data_cadastro', models.DateTimeField(db_column='data_cadastro')),
                ('login_cadastro', models.CharField(db_column='login_cadastro', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'AlunosxTurmas',
                'db_table': 'ALUNOSxTURMAS',
                'ordering': ['valor'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.IntegerField(db_column='id_curso', primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(db_column='nome_curso', max_length=200)),
                ('data_cadastro', models.DateTimeField(db_column='data_cadastro')),
                ('login_cadastro', models.CharField(db_column='login_cadastro', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'db_table': 'CURSOS',
                'ordering': ['id_curso'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateField(db_column='data_presenca')),
                ('data_cadastro', models.DateField(db_column='data_cadastro')),
                ('login_cadastro', models.CharField(db_column='login_cadastro', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Presenças',
                'db_table': 'PRESENCA',
                'ordering': ['data_cadastro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id_situacao', models.IntegerField(db_column='id_situacao', primary_key=True, serialize=False)),
                ('situacao', models.CharField(db_column='situacao', max_length=25)),
                ('data_cadastro', models.DateTimeField(blank=True, db_column='data_cadastro', null=True)),
                ('login_cadastro', models.CharField(blank=True, db_column='login_cadastro', max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Situações',
                'db_table': 'SITUACAO',
                'ordering': ['data_cadastro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id_turma', models.IntegerField(db_column='id_turma', primary_key=True, serialize=False)),
                ('id_curso', models.IntegerField(db_column='id_curso')),
                ('data_inicio', models.DateField(db_column='data_inicio')),
                ('data_termino', models.DateField(blank=True, db_column='data_termino', null=True)),
                ('data_cadastro', models.DateTimeField(db_column='data_cadastro')),
                ('login_cadastro', models.CharField(blank=True, db_column='login_cadastro', max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'db_table': 'TURMAS',
                'ordering': ['data_inicio'],
                'managed': False,
            },
        ),
    ]
