# Generated by Django 3.0 on 2021-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEscola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turmas',
            options={'managed': False, 'ordering': ['id_turma'], 'verbose_name_plural': 'Turmas'},
        ),
    ]
