# Generated by Django 3.0 on 2021-08-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEscola', '0002_auto_20210809_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alunosxturmas',
        ),
    ]
