# Generated by Django 3.0 on 2021-08-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEscola', '0003_delete_alunosxturmas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunosxturmas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(db_column='valor', decimal_places=2, max_digits=13)),
                ('valor_desconto', models.DecimalField(blank=True, db_column='valor_desconto', decimal_places=2, max_digits=3, null=True)),
                ('data_cadastro', models.DateTimeField(db_column='data_cadastro')),
                ('login_cadastro', models.CharField(db_column='login_cadastro', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'AlunosxTurmas',
                'db_table': 'ALUNOSxTURMAS',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
